services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crown-clothing-server:0.0.1.RELEASE
    restart: always
    container_name: cc-server
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret-pwd
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret-pwd
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret-pwd@mongo:27017/
      ME_CONFIG_BASICAUTH: false
